module:
  imports:
    - path: github.com/loikein/hugo-tufte
languageCode: en-US
hasCJKLanguage: true
baseurl: "https://okankonur.com/"
title: "Okan's"
canonifyurls: true
pagination:
  pagerSize: 5

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    guessSyntax: true

params:
  subtitle: "Hello, you've reached Okan's"
  favicon: "./favicon.ico"
  touchicon: "./touch-icon.png"
  codeblocksdark: false
  marginNoteInd: "⊕"
  showPoweredBy: false
  hidedate: false
  showSummary: true
  math: true
  KaTeXVersion: 0.16.4
  KaTeXCDN: "//cdn.jsdelivr.net/npm"
  sansSubtitle: false
  centerArticle: false
  social:
    twitter: "okan_konur"
    github: "okankonur"

taxonomies:
  category: categories
  series: series
  tag: tags

menu:
  nav:
    - name: Home
      weight: -110
      identifier: home
      url: /
    - name: Posts
      weight: -100
      identifier: posts
      url: /posts/
    - name: Categories
      weight: -90
      identifier: categories
      url: /categories/
    - name: About
      weight: -80
      identifier: about
      url: /about/me
    - name: Source Code
      weight: -70
      identifier: github
      url: "https://github.com/okankonur/borgen.github.io"

caches:
  images:
    dir: :cacheDir/images
